### ISSUE TITLE
usare raiplaysound per programmi regolarmente aggiornati, e.g. Fahrenheit

### ISSUE THREAD

**Issue by alexander-winkler** [timendum/raiplaysound#10]
Ciao! Ho appena scoperto questo strumento che mi sembra utilissimo per evitare il fastidio enorme creato dal fatto che la Rai si ostina a non offrire un feed RSS . Grazie mille per metterlo a disposizione!

Ho cercato di creare – senza successo – un feed per Fahrenheit (https://www.raiplaysound.it/programmi/fahrenheit). Mi pare di aver capito che questo strumento non è fatto per programmi che vengono aggiornati regolarmente. Mi interesserebbe comunque capire se fosse teoricamente possibile generare un feed per questo programma o se questo richiedesse un approccio completamente diverso. Non sono ancora riuscito a capire il modo in cui la rai mette a disposizione i loro audio, scusate quindi l'ingenuità della domanda.

Grazie ancora!

ecco ancora un item creato dal scripty `single.py`

```
<item>
      <title> La strage dei giganti</title>
      <guid>timendum-raiplaysound-ContentItem-4f4d7bc1-56d4-4ec6-8e20-5ae776cc0ea7</guid>
      <pubDate>Fri, 31 Mar 2023 16:56:00 -0000</pubDate>
      <link>https://www.raiplaysound.it/audio/2023/03/Fahrenheit-del-31032023-4f4d7bc1-56d4-4ec6-8e20-5ae776cc0ea7.html</link>
      <description>Alle 15: Guerra alla natura, Philipp Blom scrittore, giornalista, documentarista e conduttore radiofonico, ha scritto La natura sottomessa. Ascesa e declino di un'idea, Marsilio. Traduce Manuela Cotronei |  Alle 15.30 
La strage dei giganti: dieci anni di Xylella, il dramma ecologico degli ulivi. Con Daniele Rielli, scrittore,  e con Davide Barletti, regista, autore del film documentario "Il tempo dei giganti" | Alle 16: Sonia Bergamasco, Un corpo per 
tutti, Einaudi | Alle 16.33 Fahre Scuola: Manuela Ruaben, insegnante trentina, studiosa ed esperta in outdoor education | Album del giorno: Eric Bibb "Get Onboard", 2008.</description>
      <enclosure type="audio/mpeg" url="https://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=gdqdrUSXB4pPpPluss6ZW4rNQzC4weeqqEEqualeeqqEEqual"/>
      <itunes:title> La strage dei giganti</itunes:title>
      <itunes:summary>Alle 15: Guerra alla natura, Philipp Blom scrittore, giornalista, documentarista e conduttore radiofonico, ha scritto La natura sottomessa. Ascesa e declino di un'idea, Marsilio. Traduce Manuela Cotronei |  Alle 15.30 La strage dei giganti: dieci anni di Xylella, il dramma ecologico degli ulivi. Con Daniele Rielli, scrittore,  e con Davide Barletti, regista, autore del film documentario "Il tempo dei giganti" | Alle 16: Sonia Bergamasco, Un corpo per tutti, Einaudi | Alle 16.33 Fahre Scuola: Manuela Ruaben, insegnante trentina, studiosa ed esperta in outdoor education | Album del giorno: Eric Bibb "Get Onboard", 2008.</itunes:summary>
      <itunes:duration>01:43:18</itunes:duration>
      <image>
        <url>https://www.raiplaysound.it/dl/img/2021/11/24/1637759714749_2048x2048%20fahrenheit.jpg</url>
      </image>
    </item>

```

**Comment by timendum** [comment]
Ciao, in realtà questo strumento dovrebbe tranquillamente essere in grado di gestire anche programmi come Fahrenheit, però devi gestire tu l'aggiornamento quotidiano e la pubblicazione del feed (tipicamente su un server che gestisci).

Per generare il feed di Fahrenheit devi usare

```console
python .\single.py --programma https://www.raiplaysound.it/programmi/fahrenheit
```
questo crea un `fahrenheit.xml` con quello che trovi sul sito.

**Comment by alexander-winkler** [comment]
Grazie per l'aiuto! Riesco a generare il feed, ma il problema riguarda l'URL dell'audio (`<enclosure type="audio/mpeg" url="https://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=ssSlashlfSRMYGXQhORqYD89zahweeqqEEqualeeqqEEqual"/>`) che non rimanda al file bensì ad una playlist vuota. È per questo che sospettavo un problema 'sistemico'.

**Comment by timendum** [comment]
Ciao, ho appena aggiornato il codice per gestire, puoi verificare? A me sembra funzionare.

Chiaramente devi aggiornare la versione che hai sul PC per creare nuovamente il file di fahrenheit, rimane valido il comando di sopra, senza modifiche necessarie.

**Comment by alexander-winkler** [comment]
perfetto, grazie mille!
