### ISSUE TITLE
in <pubDate> appare la data di create_data

### ISSUE THREAD

**Issue by alexander-winkler** [timendum/raiplaysound#11]
Grazie alle modifiche fatte per #10 riesco ad ascoltare i miei programmi nel mio podcatcher (https://github.com/alexander-winkler/raiPodcasts). I feed che vengono creati (con `single.py`) hanno però, nel elemento `<pubDate>`, sempre la data dell'ultimo aggiornamento invece della data della pubblicazione della puntata, il che crea una certa confusione perché le singole puntate non vengono ordinate correttamente.

**Comment by timendum** [comment]
Hai decisamente ragione, è lo stesso problema segnato in #3.

Commentare queste righe in single.py dovrebbe sistemare il problema

            if dupdate <= last_update:
                dupdate = last_update + timedelta(seconds=1)

Purtroppo le date di pubblicazioni non sono sempre affidabili, quindi cerco di aggiustarle ma spacco questi casi.

Se ci fosse un chiaro modo di identificare i casi, potrei farci logica.

**Comment by timendum** [comment]
Ora dovrebbe essere sistemato, in particolare se vuoi mantenere le date originali, usa l'opzione `--dateok` in `single.py`.
