### ISSUE TITLE
Add support for Hevreka podcast

### ISSUE THREAD

**Issue by tekvsakdan** [timendum/raiplaysound#12]
Can you add support for https://www.raiplaysound.it/programmi/hevreka? I tried to generate xml but it failed

```
$ python3 single.py https://www.raiplaysound.it/programmi/hevreka
Skipped programmi: https://www.raiplaysound.it/programmi/hevreka (programmi radio)

```

**Comment by tekvsakdan** [comment]
I have removed the `"programmi radio" `in the code and it works now. I don't think `single.py `needs this restriction.

**Comment by timendum** [comment]
The script already handles this case with an option

You should run

    single.py --programma https://www.raiplaysound.it/programmi/hevreka

**Comment by tekvsakdan** [comment]
Thanks. It works like a charm.
