### ISSUE TITLE
Automate running scripts on a daily/weekly basis 

### ISSUE THREAD

**Issue by loucasal** [timendum/raiplaysound#2]
Ciao, complimenti per l'iniziativa!

Would it be possible to automatically run the scripts on a more regular basis, to allow users to receive episodes closer to their actual publication?

**Comment by timendum** [comment]
Yeah, definitively, some users did it for one or two podcast.

**Comment by loucasal** [comment]
Sorry, I wasn't clear - of course this can be done when self-hosting, I was wondering if this is not done on your instance for specific reasons (e.g. to avoid being banned/rate limited from the RaiPlay Sound server?).
