### ISSUE TITLE
Support for Giornale Radio

### ISSUE THREAD

**Issue by mu22le** [timendum/raiplaysound#20]
Ciao, e grazie per tutti i feed che hai messo a disposizione!  Pensi che potresti aggiungere i feed per i giornali radio (GR1, GR2 e GR3) o questi richiederebbero un aggiornamento troppo frequente?

**Comment by timendum** [comment]
Lo script è pronto e farlo girare giornalmente includendo il GR è fattibile.

Però dovrei seguirlo quotidianamente, anzi, più volte al giorno. Qualche
altro utente lo fa, ma non io.

**Comment by mu22le** [comment]
Grazie per il feedback. Cerchero' il modo di installare lo script localmente.
