### ISSUE TITLE
Podcast mancanti (es. 610)

### ISSUE THREAD

**Issue by provolino** [timendum/raiplaysound#21]
Ciao, intanto complimenti per l'iniziativa, confesso che mi è stata veramente comoda perché non sopportavo l'idea di dover installare un'applicazione dedicata solo per i podcast rai (con conseguente spreco di spazio e batteria) quando ho tutti gli altri comodamente su AntennaPod.

Ho però notato che il tuo elenco non è completo, manca ad esempio il feed di 610 (la trasmissione comica di Lillo & Greg) che è correttamente disponibile sul sito ufficiale.

Potresti gentilmente aggiungerla o darmi l'indirizzo da inserire come feed?

Grazie mille :)

**Comment by timendum** [comment]
Ciao e grazie dei complimenti.

610 è escluso dai file generati perché si aggiorna quotidianamente.

Puoi però comunque usare programma per generare quei feed in questo modo:

    python single.py --programma https://www.raiplaysound.it/programmi/lilloegreg610

Chiaramente devi installarlo da qualche parte e farlo girare tutti i giorni, affinché sia utile.
