### ISSUE TITLE
Add a "reverse" switch to keep more recent episodes in the head of the generated XML?

### ISSUE THREAD

**Issue by mrcrutch** [timendum/raiplaysound#22]
Hi all and many thanks for all your fantastic work!
As in the subject, maybe would be nice to add a "--reverse" switch or something similar to let the user choose to keep more recent episodes in the head of the generated file, so that the player shows them in the top of the list.
Just a suggestion. If I'd time in the next days I'd try to propose a solution :)

**Comment by timendum** [comment]
It's a good idea, if you are planning to create a pull request, i'll wait for your code.

Please add a new cli argument at least in `single.py`
