### ISSUE TITLE
Alternative way to discover available available podcasts

### ISSUE THREAD

**Issue by svalo** [timendum/raiplaysound#23]
I was searching a podcast (https://www.raiplaysound.it/programmi/revolution) and it did now show up even when `skip_programmi=False` and `skip_film=False` are given in `all.py`. When I do use `single.py` with the URL, the xml is created correctly.

In `all.py` output the program does not show up so I think it may be because it is not reachable from `generi` URL.

Would you consider using sitemaps to discover available podcasts? I noticed that a general one is available at https://www.raiplaysound.it/sitemap.archivio.indice.xml and points to other sitemaps, one per category and then one per podcast.

The program I am interested in is available in sitemap https://www.raiplaysound.it/sitemap.archivio.programmi.xml but not in https://www.raiplaysound.it/sitemap.archivio.generi.xml

I may propose a PR if you think it's valuable

**Comment by timendum** [comment]
Hi,
I can work on it but if you are willing to produce a PR that browse site
map, it's welcome.

Either add it to the discovery in all.py or create a new file.

Thanks!
