### ISSUE TITLE
Add support for podcasts with separate seasons

### ISSUE THREAD

**Issue by loucasal** [timendum/raiplaysound#4]
Some podcasts (e.g. [Alle otto della sera](https://www.raiplaysound.it/programmi/alleottodellasera)) have different 'seasons' and/or playlists on the RaiPlay Sound website. Currently, the [feed](https://timendum.github.io/raiplaysound/alleottodellasera.xml) includes the first 'season' only.

**Comment by timendum** [comment]
The script supports it, just not very clearly.

For "Alle otto della sera" you can find:
- https://timendum.github.io/raiplaysound/scrittoriallasbarra.xml
- https://timendum.github.io/raiplaysound/paradiso-gliultimi4canti.xml
- and so on

**Comment by gpz500** [comment]
It seems to me that there are podcasts which work differently. E.g. [Hollywood Party - Il cinema alla radio](https://www.raiplaysound.it/programmi/hollywoodparty-ilcinemaallaradio) has a "season selector" that gives access to different episodes than playlists: the season selector is organized year-by-year while the playlists are organized by argument.
In short: seasons != playlists.

It would be nice if your scripts were able to address even seasons. Just to start 😜: I noted that every season has an entry in the "filters" list in the main JSON, with filters[0] related to the last/current season, filters[1] for the penultimate, and so on.
