### ISSUE TITLE
Some podcasts are not scraped correctly

### ISSUE THREAD

**Issue by loucasal** [timendum/raiplaysound#6]
Some feeds (e.g. [Wikiradio](https://timendum.github.io/raiplaysound/wikiradio.xml)) fail in scraping the episodes correctly. All episodes are returned with the same size (129 B) and cannot be downloaded/streamed. Possibly linked to issue #3, as it affects the same podcast.

**Comment by timendum** [comment]
That's what the original provider (ie: raiplay sound) server, a 128 byte [M3u file](https://en.wikipedia.org/wiki/M3U) that leads to the m3u8 playlist.

If I open the url with VLC or a podcast app, it works.

**Comment by loucasal** [comment]
I don't know if there is much you can do about it, but FYI both AntennaPod and Google Podcasts fail to parse the feed (the latter even refuses to subscribe to the podcast). I will check with the AntennaPod devs whether there is any way of supporting this feed.

**Comment by timendum** [comment]
I'm sorry but the audio is provided by raiplay, I'm not interested in re-hosting or re-encoding it.

This project only offers convenient xml files that link to the audio on raiplay.

**Comment by loucasal** [comment]
Oh I wasn't implying that, I'm only wondering whether feeds can be optimised so that they can be parsed by a majority of podcatchers. In any case I'm out of my depth, so I will let you know once I hear back from the AP team.

**Comment by loucasal** [comment]
Here is the AP maintainer's reply (from AntennaPod/AntennaPod#6143):
> I think that podcast creator should fix their feed. The enclosure claims to be `audio/mp3` but is then actually a `m3u` playlist that links to the actual media file. Why don't they just link the media file directly like everyone else? That feed also fails pretty much all tests on [castfeedvalidator](https://www.castfeedvalidator.com/validate.php?url=https://timendum.github.io/raiplaysound/wikiradio.xml). I don't think AntennaPod should work around broken feeds even more than it already does... Especially if the feed is _so extremely_ broken.
