### ISSUE TITLE
Non funziona su Castamatic

### ISSUE THREAD

**Issue by pietrodelbu** [timendum/raiplaysound#7]
Utilizzando Castamatic Incollando il link per aggiungere un nuovo podcast, come da istruzioni, viene trovato il podcast ma non vengono visualizzate le puntate.

**Comment by timendum** [comment]
Ciao, puoi dirmi di più? Di che podcast si tratta? Che errore ricevi?

**Comment by pietrodelbu** [comment]
Ciao, ho provato ad esempio con "io ero il milanese" e con "labanof". Questo è un esempio dello screen del programma. Non c'è nessun errore. Come detto viene "trovato" il podcast ma l'elenco degli episodi è vuoto. 
![image](https://user-images.githubusercontent.com/57495930/198959442-08b4b27a-3125-4754-acbd-2b3ce66090a7.jpeg)

**Comment by timendum** [comment]
Ciao, ho fatto una fix, modificando il mimetype. Puoi verificare se è risolto?

**Comment by pietrodelbu** [comment]
Uhm, no, ho provato a fare un refresh del feed ma non sembra sia cambiato nulla. Gli episodi non vengono mostrati.

**Comment by timendum** [comment]
Prova a toglierlo e rimetterlo, so che sembra stupido ma non essendo arrivati nuovi episodi, ma cambiato un attributo di un allegato, potrebbe essere che il lettore non se ne accorga.

**Comment by pietrodelbu** [comment]
Mi spiace ma niente... ho provato anche con il altro podcast... copiando l'url trova il titolo, prende su anche l'immagine, ma non raccoglie l'elenco degli episodi.

![image](https://user-images.githubusercontent.com/57495930/200674501-ca69aa55-bdbc-48f2-a852-26471dca4eec.jpeg)

**Comment by timendum** [comment]
Ciao, ho contattato lo sviluppatore di Castamatic, purtroppo è un problema irrisolvibile, l'app ha bisogno di una URL con estensione (es: `https://www.rai.it/audio.mp3`) per capire il tipo di file, ma io non posso chiedere alla Rai di cambiare le loro URL.

Mi spiace!

**Comment by pietrodelbu** [comment]
@timendum Tutto Chiaro grazie, quindi in teoria con quali APP di Podcast per iOs tu hai fatto dei test o per come sono fatte, secondo te funziona? Grazie

**Comment by timendum** [comment]
Non ho testato su un iPhone, perché non ne ho a disposizione, ma sono
convinto che su Overcast dovrebbe andare.
