### ISSUE TITLE
Problema con Overcast

### ISSUE THREAD

**Issue by DzigaVertoff** [timendum/raiplaysound#8]
L'importazione funziona, il podcast viene riconosciuto ma nelle singole puntate esce l'errore "Invalid audio file". Ho provato con il podcast [Hollywood Party](https://timendum.github.io/raiplaysound/hollywoodparty-ilcinemaallaradio.xml):
![image](https://user-images.githubusercontent.com/32367225/200177841-cfdded3c-2ea2-4ef6-8d4c-e59d52650884.jpeg)

**Comment by timendum** [comment]
Ciao, ho fatto una fix, modificando il mimetype. Puoi verificare se è risolto?

**Comment by DzigaVertoff** [comment]
> Ciao, ho fatto una fix, modificando il mimetype. Puoi verificare se è risolto?

Niente, non va. Ho provato anche a importarlo di nuovo ma non funziona comunque

**Comment by TorgeTorge** [comment]
Anch’io ho lo stesso problema, non riesco a riprodurre il contenuto del podcast.
Edit-
Ho provato a scaricare il file media del podcast direttamente dal file .xml ma scarica un playlist .m3u8, non direttamente il file audio.
Se utilizzo ffmpeg noto che estrapola diversi file .aac dalla playlist per poi ricomporli in un unico file.
Non so se questo possa essere d'aiuto...
![Cattura](https://user-images.githubusercontent.com/77051049/209736542-e841429e-7829-485e-a694-0a1723324b68.PNG)

**Comment by DzigaVertoff** [comment]
Update:
Fra le nuove puntate ne ha scaricata soltanto una, per le altre mi dice sempre "invalid audio file". 
La puntata che è stata correttamente scaricata è "Vacanze romane di William Wyler" del 13 febbraio.
![image](https://user-images.githubusercontent.com/32367225/220543722-ede202b6-b6f0-4096-a642-6adc6f8e1105.jpeg)

**Comment by timendum** [comment]
In questi casi **penso** si tratti della compatibilità tra il formato audio offerto da RaiPlay Sound e l'applicazione di podcast.

Controllando dallo screenshot, l'oggetto che va è un semplice file mp3, mentre gli altri sono stream [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming).

Andrebbero convertiti da qualche parte (ad esempio con ffmpeg) e poi pubblicati nel feed gli mp3.

Lascio aperta la issue, sperando che possano essere utile ad altri, ma non sarà risolta da questo progetto.

**Comment by timendum** [comment]
Buone notizie, grazie alla fix fatta per #10 potrei aver sistemato anche questo, qualcuno può confermare?

**Comment by DzigaVertoff** [comment]
Confermo, adesso funziona. Grazie

**Comment by timendum** [comment]
Ottimo, chiudo.
