### ISSUE TITLE
Radio3Mondo missing

### ISSUE THREAD

**Issue by pfontana77** [timendum/raiplaysound#9]
It is possible to include also Radio3mondo in the list?

Thanks.

Best regards.

**Comment by manmatteo** [comment]
Vedi https://github.com/timendum/raiplaysound/issues/5: nel sito di @timendum non sono generati i feed per i programmi radio, se vuoi puoi farlo tu a mano

**Comment by timendum** [comment]
Confermo, questi programmi cambiano tutti i giorni e non è obbiettivo di questo progetto starci dietro.

Consiglio in questo caso di installare il progetto da qualche parte e pianificare il refresh secondo il proprio bisogno.
